#define STALLED 0
#define MOVING_FORWARD 1
#define MOVING_BACKWARD 2
#define HARVESTING 3
#define MAX_SERVO_ANGLE 60
#define AHIGH 200
#define ALOW 100

// Analog Pins
#define IR_SENSOR_LEFT_PIN A0
#define IR_SENSOR_RIGHT_PIN A1

#define COMMAND_HARVEST_IN_PIN A5
#define COMMAND_FORWARD_IN_PIN A4
#define COMMAND_BACKWARD_IN_PIN A3

#define REPLY_ACK_OUT_PIN 11
#define REPLY_DONE_OUT_PIN 12

// Digital Pins
#define TURN_MOTOR_LEFT_PIN 4
#define TURN_MOTOR_RIGHT_PIN 3

#define BACKWARD_MOTOR_PIN 8
#define FORWARD_MOTOR_PIN 7

#define HORIZONTAL_WRIST_PIN 5
#define VERTICAL_WRIST_PIN 10
#define HORIZONTAL_ARM_PIN 6
#define VERTICAL_ARM_PIN 9

#define LED_PIN 13

// Constants
#define VERTICAL_ARM_MIN_ANGLE 40
#define VERTICAL_ARM_MAX_ANGLE 80
